# Generated by Django 4.2.10 on 2024-02-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_category_book_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='post.book')),
            ],
        ),
    ]
