# Generated by Django 4.2.10 on 2024-02-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_books',
            new_name='post',
        ),
    ]
